import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:tanitama/core/commons/constants.dart';

final textTheme = TextTheme(
  displayLarge: GoogleFonts.nunito(
      fontSize: 93,
      fontWeight: FontWeight.w300,
      letterSpacing: -1.5,
      color: darkTextColor),
  displayMedium: GoogleFonts.nunito(
      fontSize: 58,
      fontWeight: FontWeight.w300,
      letterSpacing: -0.5,
      color: darkTextColor),
  displaySmall: GoogleFonts.nunito(
      fontSize: 46, fontWeight: FontWeight.w400, color: darkTextColor),
  headlineMedium: GoogleFonts.nunito(
      fontSize: 33,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: darkTextColor),
  headlineSmall: GoogleFonts.nunito(
      fontSize: 23, fontWeight: FontWeight.w400, color: darkTextColor),
  titleLarge: GoogleFonts.nunito(
      fontSize: 19,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.15,
      color: darkTextColor),
  titleMedium: GoogleFonts.nunito(
      fontSize: 15,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.15,
      color: darkTextColor),
  titleSmall: GoogleFonts.nunito(
      fontSize: 13,
      fontWeight: FontWeight.w500,
      letterSpacing: 0.1,
      color: darkTextColor),
  bodyLarge: GoogleFonts.nunito(
      fontSize: 15,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.5,
      color: darkTextColor),
  bodyMedium: GoogleFonts.nunito(
      fontSize: 13,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.25,
      color: darkTextColor),
  labelLarge: GoogleFonts.nunito(
      fontSize: 13,
      fontWeight: FontWeight.w500,
      letterSpacing: 1.25,
      color: darkTextColor),
  bodySmall: GoogleFonts.nunito(
      fontSize: 12,
      fontWeight: FontWeight.w400,
      letterSpacing: 0.4,
      color: darkTextColor),
  labelSmall: GoogleFonts.nunito(
      fontSize: 10,
      fontWeight: FontWeight.w400,
      letterSpacing: 1.5,
      color: darkTextColor),
);
